package com.synchrony.synchronyswat.api.enums;

public enum ValidatorOperation {
    KEY_PRESENTS, EQUALS, NOT_EQUALS, NOT_NULL, HAS_STRING, SIZE, EMPTY, NOT_EMPTY, HAS_ITEM, GREATER_THAN,LESS_THAN,GREATER_THAN_OR_EQUALTO,LESS_THAN_OR_EQUALTO, HAS_XPATH;
}
